parameters: {}
environment: {}
packages:
    - name: dhrn
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: addresses 
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: zipcounty 
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: sendmail
          binary: false
          main: ""
          runtime: python:default
          web: true
          parameters: {}
          environment:
            MAILTRAP_API_TOKEN: "${MAILTRAP_API_TOKEN}"
            MAILTRAP_SENDER_ADDRESS: "${MAILTRAP_SENDER_ADDRESS}"
            MAILTRAP_TO_ADDRESS: "${MAILTRAP_TO_ADDRESS}"
          annotations: {}
          limits: {}