name: DO functions deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy function
        run: ls ${{ github.workspace }}
      - run: cd dhrn-functions
      - name: Setup serverless
        run: doctl serverless install      
      - name: Connect to serverless
        run: doctl serverless connect
      - name: Deploy function
        run: doctl serverless deploy dhrn-functions --remote-build
        env:
          MAILTRAP_API_TOKEN: ${{ secrets.MAILTRAP_API_TOKEN }}
          MAILTRAP_SENDER_ADDRESS: ${{ secrets.MAILTRAP_SENDER_ADDRESS }}
          MAILTRAP_TO_ADDRESS: ${{ secrets.MAILTRAP_TO_ADDRESS }}

